{
 "title": "Change Hair Style",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Change Hair Colour (count)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "change_hair_style_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Change Hair Colour (Total time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "change_hair_style_request_processing_seconds_sum"
    }
   ]
  },
  {
   "title": "Change Hair Colour (average)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "change_hair_style_request_processing_seconds_sum / change_hair_style_request_processing_seconds_count"
    }
   ]
  }
 ]
}