{
 "title": "Upload Picture",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Detect Face Landmarks (average time)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "detect_face_landmarks_request_processing_seconds_sum / detect_face_landmarks_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Detect Face (average time)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "detect_face_request_processing_seconds_sum / detect_face_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Detect Face Shape (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "detect_face_shape_request_processing_seconds_sum / detect_face_shape_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Save Picture (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "save_picture_request_processing_seconds_sum / save_picture_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Picture Info (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "get_picture_info_request_processing_seconds_sum / get_picture_info_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Detect Face Landmarks (count)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "detect_face_landmarks_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Detect Face (count)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "detect_face_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Detect Face Shape (count)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "detect_face_shape_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Save Picture (count)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "save_picture_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Picture Info (count)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "get_picture_info_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Detect Face Landmarks (sum)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "detect_face_landmarks_request_processing_seconds_sum"
    }
   ]
  },
  {
   "title": "Detect Face (sum)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "detect_face_request_processing_seconds_sum"
    }
   ]
  },
  {
   "title": "Detect Face Shape (sum)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "detect_face_shape_request_processing_seconds_sum"
    }
   ]
  },
  {
   "title": "Save Pictures (sum)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "save_picture_request_processing_seconds_sum"
    }
   ]
  },
  {
   "title": "Picture Info (sum)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "get_picture_info_request_processing_seconds_sum"
    }
   ]
  },
  {
   "title": "Upload Picture (Average time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(detect_face_landmarks_request_processing_seconds_sum / detect_face_landmarks_request_processing_seconds_count) + (detect_face_request_processing_seconds_sum / detect_face_request_processing_seconds_count) + (detect_face_shape_request_processing_seconds_sum / detect_face_shape_request_processing_seconds_count) + (get_picture_info_request_processing_seconds_sum / get_picture_info_request_processing_seconds_count) + (save_picture_request_processing_seconds_sum / save_picture_request_processing_seconds_sum)"
    }
   ]
  }
 ]
}