name: Flutter CI
on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1.4.0
      
      # Get dependencies
      - run: flutter pub get
      
      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .
      
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
      
      # Run tests
      - run: flutter test
      
      # Build apk.
      - run: flutter build apk
        
        # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
    
